config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts
  get 'home/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'

  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  #usuarios  registrados puede dejar comentarios en la noticias
 
 

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @post = Post.find(params[:comment][:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@post), notice: "Comentario creado exitosamente" }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to @post, alert: "Error al crear Comentario" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comentario Editado exitosamente" }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comentario eliminado correctamente" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :post_id)
    end
    def set_post
      @post = Post.find(params[:post_id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= comment.post_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, class: "form") do |form| %>
  <% if comment.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :content, "Contenido", class: "form-label fs-5 fw-bold text-light" %>
    <%= form.text_field :content, class: "form-control rounded-pill" %>
  </div>

  <div class="mb-3">
    <%= form.label :user_id, class: "form-label fs-5 fw-bold text-light" %>
    <%= form.text_field :user_id, class: "form-control rounded-pill" %>
  </div>

 

  <div class="text-center input-group">
     <%= form.submit "Actualizar", class: " btn btn-primary" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="row justify-content-center align-items-center" style="height: 80vh;">
  <div class="col-lg-6 col-md-8 col-sm-10">
    <div class="p-3 rounded-3 shadow glass">
      <div class="card-body">
        <h1 class="card-title text-center text-warning">Editar Comentario</h1>

        <%= render "form", comment: @comment %>

        <div class="text-center justify-content-center input-group mt-3">
          <%= link_to "Ver Comentario", @comment, class: "btn btn-primary" %>
          <%= link_to "Volver a Comentarios", comments_path, class: "btn btn-warning" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/comments/index.html.erb
<div class="d-flex justify-content-center align-items-center" style="height: 80vh;">
  <div class="card glass2 bg-transparent w-100">
    <div class="card-body">
      <h1 class="card-title text-warning">Comentarios</h1>
      <div class="table-responsive">
        <table class="table table-striped ">
          <thead class="table-dark">
            <tr>
              <th>ID</th>
              <th>Contenido</th>
              <th>Usuario</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @comments.each do |comment| %>
              <tr>
                <td><%= comment.id %></td>
                <td><%= comment.content %></td>
                <td><%= comment.user.email %></td>
                <td><%= link_to "", comment, class: "fa-sharp fa-solid fa-eye text-decoration-none" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= link_to "Volver a las noticias", posts_path, class: "btn btn-primary glow-on-hover bg-primary" %>
    </div>
  </div>
</div>

app/views/comments/new.html.erb
<div class="row justify-content-center align-items-center" style="height: 80vh;">
  <div class="col-lg-6 col-md-8 col-sm-10">
    <div class="p-3 rounded-3 shadow-lg glass2">
      <div class="card-body text-center text-light">
        <h3><%= @comment.content %></h3>
        <h6>Publicado por: <%= @comment.user.email %></h6>

        <div class="text-center justify-content-center input-group mt-4">
          <%= link_to "Editar Comentario", edit_comment_path(@comment), class: "btn btn-sm btn-secondary" %>
          <%= link_to "Volver a comentarios", comments_path, class: "btn btn-sm btn-warning" %>
          <%= button_to "Eliminar comentario", @comment, method: :delete, class: "btn btn-sm rounded-0 rounded-end btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/comments/show.html.erb
<div class="row justify-content-center align-items-center" style="height: 80vh;">
  <div class="col-lg-6 col-md-8 col-sm-10">
    <div class="p-3 rounded-3 shadow-lg glass2">
      <div class="card-body text-center text-light">
        <h3><%= @comment.content %></h3>
        <h6>Publicado por: <%= @comment.user.email %></h6>

        <div class="text-center justify-content-center input-group mt-4">
          <%= link_to "Editar Comentario", edit_comment_path(@comment), class: "btn btn-sm btn-secondary" %>
          <%= link_to "Volver a comentarios", comments_path, class: "btn btn-sm btn-warning" %>
          <%= button_to "Eliminar comentario", @comment, method: :delete, class: "btn btn-sm rounded-0 rounded-end btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>