config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts
  get 'home/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'

  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  #solo los autores y administradores pueden crear noticias
  before_action only: [:destroy] do
    authorize_request(["admin"])
   end
  

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.usser = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "La noticia a sido creada" }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "La noticia a sido Editada" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "La noticia a sido eliminada" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :title, :content, :user_id, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "form") do |form| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :image, "Imagen", class: "form-label fs-5 fw-bold " %>
    <%= form.text_field :image, class: "form-control " %>
  </div>

  <div class="mb-3">
    <%= form.label :title, "Titulo", class: "form-label fs-5 fw-bold" %>
    <%= form.text_field :title, class: "form-control " %>
  </div>

  <div class="mb-3">
    <%= form.label :content, "Contenido", class: "form-label fs-5 fw-bold" %>
    <%= form.text_area :content, class: "form-control " %>
  </div>


  <%= form.label current_user.email, "Usuario", class: "form-label fs-5 fw-bold " %>
  <div class="input-group">
     <%= form.text_field current_user.email, class: "form-control " %>
  </div>
  <p></p>
        <%= form.submit "Crear Noticia", class: " btn btn-primary  bg-primary " %>

<% end %>

app/views/posts/_post.html.erb
<div class="row justify-content-center align-items-center mt-5">
  <div class="col-lg-5 col-md-8 col-sm-10">
    <div id="<%= dom_id(post) %>" class="glass p-3 rounded-3 shadow  mb-3">
      <div class="glow-on-hover">
        <p>
          <strong>Titulo:</strong>
          <%= post.title %>
        </p>

        <p>
          <strong>Descripcion:</strong>
          <%= post.content %>
        </p>

        <p>
          <strong>Usuario:</strong>
          <%= post.user.email %>
        </p>
        <p>
          <%= image_tag(post.image, style: "max-width: 100%;", class: "img-fluid rounded") %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
 

<div class="row justify-content-center align-items-center" style="height: 80vh;">
  <div class="col-lg-6 col-md-8 col-sm-10">
    <div class="p-3 rounded-3 shadow glass">
      <div class="card-body">
        <h1 class="card-title text-center text-warning">Editar Noticia</h1>

        <%= render "form", post: @post %>

        <div class="text-center mt-3 input-group justify-content-center">
          <%= link_to "Ver Noticias", @post, class: "btn btn-primary" %>
          <%= link_to "Volver a Noticias", posts_path, class: "btn btn-warning" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="d-flex justify-content-between m-3" >
<h2 class="text-warning m-0" >Noticias</h2>
<%= link_to "Nueva Noticia", new_post_path, class:"btn btn-danger ", style:"background-color:#0dcaf0" %>
</div>

<div class="row">
  <% @posts.each do |post| %>
    <div class="col-12 col-md-6 col-lg-3 mb-3">
      <div class="card glow-on-hover bg-transparent border-0 shadow glass" style="min-height:100%">
        <div class="card-header bg-primary bg-opacity-50 bg-gradient text-light">
          <h2 class="card-title text-light"><%= post.title %></h2>
        </div>
        <div class="card-body glass">
         
          <p  ><%= post.content %></p>
        </div>
       <div class="card-scrollable-comments scrollbar-danger p-1 glass" style="max-height: 150px; overflow-y: auto;">
  <% post.comments.each do |comment| %>
    <div class="comment   p-1 m-2 ">
      <p class="comment-content text-dark"><%= comment.content %></p>
      <p class="comment-info text-secondary" style="font-size:12px;">
        Autor: <%= comment.user.email %>
        el <%= comment.created_at.strftime("%d/%m/%Y a las %H:%M") %>
      </p>
    </div>
  <% end %>
</div>
  <div class="card-comment-form glass">
  <%= form_with(model: [post, Comment.new], url: comments_path, local: true) do |form| %>
    <%= form.hidden_field :post_id, value: post.id %>
    <div class="field px-3 py-2">
      <%= form.text_area :content, rows: 2, style: "resize: none;", class: "form-control p-1    ", placeholder: "Escribe tu comentario" %>
    </div>
    <div class="text-center">
      <%= form.submit "Comentar", class:"btn btn-primary btn-sm rounded-pill shadow mb-2" %>
    </div>
  <% end %>
</div>
  <div class="card-footer  d-flex justify-content-between "; style="font-size:12px">
    <%= time_ago_in_words(post.created_at, locale: :es) %>
    Autor: <%= post.user.email %>
    <%= link_to "Ver Noticia", post %>
      </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="row justify-content-center align-items-center" style="height: 80vh;">
  <div class="col-lg-6 col-md-8 col-sm-10">
    <div class=" glass p-4 rounded-4 shadow-lg">
      <div class="card-body">
        <h1 class="card-title text-center text-warning shadow-text">Nueva Noticia</h1>

        <%= render "form", post: @post %>

        <div class="text-center mt-3">
          <%= link_to "Volver a noticias", posts_path, class: "btn btn-sm btn-primary glow-on-hover rounded-pill bg-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row justify-content-center align-items-center mt-5">
<%= render @post %>
  <div class="input-group justify-content-center shadow">
    <%= link_to "Editar Noticia", edit_post_path(@post), class: "btn btn-primary" %>
    <%= link_to "Volver a Noticia", posts_path, class: "btn btn-warning" %>
    <%= button_to "Eliminar Noticia", @post, method: :delete, class: "btn btn-primary  " %>
  </div>
</div>